# Generated by Django 3.0.2 on 2020-01-31 01:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('chordpro_data', models.TextField()),
                ('tags', models.ManyToManyField(to='catalog.Tag')),
            ],
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=256)),
                ('type', models.CharField(choices=[('YOUTUBE', 'Youtube'), ('WEB_PAGE', 'Web Page')], max_length=16)),
                ('Song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Song')),
            ],
        ),
    ]
